version: '3'

services:

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: adam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vigilate
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"